"""add payslips table

Revision ID: 2d45ee22f0af
Revises: 7b0787249867
Create Date: 2026-09-23 13:05:27.602017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2d45ee22f0af'
down_revision: Union[str, Sequence[str], None] = '7b0787249867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payslips',
    sa.Column('employee_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('period_label', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gross_total', sa.Float(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payslips')
    # ### end Alembic commands ###
