"""add treasury, banking, and invoices tables

Revision ID: 30bceb9de089
Revises: b2c3c5a0bb3c
Create Date: 2026-09-23 11:22:37.887877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '30bceb9de089'
down_revision: Union[str, Sequence[str], None] = 'b2c3c5a0bb3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_country'), 'bank_accounts', ['country'], unique=False)
    op.create_table('treasury_entries',
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('recorded_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('counterparty', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treasury_entries_country'), 'treasury_entries', ['country'], unique=False)
    op.create_table('bank_loans',
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('lender', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('principal', sa.Float(), nullable=False),
    sa.Column('remaining', sa.Float(), nullable=False),
    sa.Column('monthly_payment', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_transactions',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_account_id'), 'bank_transactions', ['account_id'], unique=False)
    op.create_table('invoices',
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('doc_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('client_passport', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('client_mf', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('service_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('tva_rate', sa.Float(), nullable=False),
    sa.Column('timbre', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('items_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_country'), 'invoices', ['country'], unique=False)
    op.create_index(op.f('ix_invoices_number'), 'invoices', ['number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_country'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_bank_transactions_account_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_table('bank_loans')
    op.drop_index(op.f('ix_treasury_entries_country'), table_name='treasury_entries')
    op.drop_table('treasury_entries')
    op.drop_index(op.f('ix_bank_accounts_country'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
