"""create clients table

Revision ID: 79deff806374
Revises: 
Create Date: 2026-09-22 21:16:37.430588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '79deff806374'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('given_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('surname', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('passport_number', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('place_of_birth', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('date_of_issue', sa.Date(), nullable=True),
    sa.Column('date_of_expiry', sa.Date(), nullable=True),
    sa.Column('issued_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_passport_number'), 'clients', ['passport_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_passport_number'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
