"""add client contact/business fields and client_files table

Revision ID: b2c3c5a0bb3c
Revises: 79deff806374
Create Date: 2026-09-23 11:21:32.638458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b2c3c5a0bb3c'
down_revision: Union[str, Sequence[str], None] = '79deff806374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('uploaded_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_files_client_id'), 'client_files', ['client_id'], unique=False)
    op.add_column('clients', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True))
    op.add_column('clients', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    op.add_column('clients', sa.Column('entreprise_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    op.add_column('clients', sa.Column('code_fiscal', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('clients', sa.Column('visa_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('clients', sa.Column('visa_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('clients', sa.Column('client_relation', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('clients', sa.Column('prix_dossier', sa.Float(), nullable=True))
    op.add_column('clients', sa.Column('paiement_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('clients', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'currency')
    op.drop_column('clients', 'paiement_type')
    op.drop_column('clients', 'prix_dossier')
    op.drop_column('clients', 'client_relation')
    op.drop_column('clients', 'visa_type')
    op.drop_column('clients', 'visa_status')
    op.drop_column('clients', 'code_fiscal')
    op.drop_column('clients', 'entreprise_name')
    op.drop_column('clients', 'email')
    op.drop_column('clients', 'phone')
    op.drop_index(op.f('ix_client_files_client_id'), table_name='client_files')
    op.drop_table('client_files')
    # ### end Alembic commands ###
