"""drop unused bank_loans table

Revision ID: cda5591e20e5
Revises: 2d45ee22f0af
Create Date: 2026-09-24 09:35:26.090732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cda5591e20e5'
down_revision: Union[str, Sequence[str], None] = '2d45ee22f0af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_loans')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_loans',
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lender', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('principal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('remaining', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('monthly_payment', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], name=op.f('bank_loans_account_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bank_loans_pkey'))
    )
    # ### end Alembic commands ###
